server:
  port: 8011

spring:
  application:
    name: ms-provider-consul-payment
  # 把服务注册进consul
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        # hostname: 127.0.0.1
        service-name: ${spring.application.name}
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率介于0到1之间，1表示全部采集
      probability: 1