server:
  port: 83

spring:
  application:
    name: ms-consumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址

# 消费者要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://ms-provider-nacos

management:
  endpoints:
    web:
      exposure:
        include: "*"