server:
  port: 9527

spring:
  application:
    name: ms-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # hostname: 127.0.0.1
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route  # 路由ID，没有固定格式，但是要唯一，建议配合服务名
          # uri: http://localhost:8011   # 匹配后提供服务的地址
          uri: lb://ms-provider-consul-payment  # 匹配后提供访问的路由地址
          predicates:
            # - After=2020-05-05T17:52:46.754+08:00[Asia/Shanghai]  # 在该时间点之后生效
            - Path=/payment/get/**  # 断言，路径相匹配的，进行路由
            # - Cookie=username,zzyy  # 必须携带cookie，并且按照后边的规则
            # - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性，并且值为整数的正则表达式
        - id: payment_route2  # 路由ID，没有固定格式，但是要唯一，建议配合服务名
          # uri: http://localhost:8011   # 匹配后提供服务的地址
          uri: lb://ms-provider-consul-payment  # 匹配后提供访问的路由地址
          predicates:
            - Path=/payment/lb/**  # 断言，路径相匹配的，进行路由