server:
  port: 84

spring:
  application:
    name: ms-consumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假设被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

# 消费者要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://ms-provider-nacos

# 激活sentinel对feign的支持
# 注意，如果不加这个，sentinel无法发现服务提供者已经挂机，那么消费者直接报错，甚至被拖垮
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"