server:
  port: 3344

spring:
  application:
    name: ms-config
  cloud:
    config:
      server:
        git:
          # 在github上git仓库的名字
          uri: https://github.com/myturn0/ms-config.git
      # search-paths:
        # -springcloud-config
    # 读取分支
    # label: master
  # rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


# 暴露bus刷新配置的端点，需要pom中加入actuator包
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"